### ISSUE TITLE
playbackRate only update AUDIO/VIDEO after changing currentTime

### ISSUE THREAD

**Issue by barata0** [bbc/VideoContext#29] opened 2017-03-21 18:14 UTC
When
`ctx.playbackRate++;`
The currentPosition is increased properly but the audio/video do not speed up. 

Work around: The playbackRate only changes the VIDEO speed after 
`ctx.currentTime = ctx.currentTime;`

Ps. Tried with the video Big_Buck_Bunny_4K.webm.160p.webm

**Comment by MatthewShotton** [comment] 2017-03-22 10:45
Hi!

Thanks for finding this one. It looks like it was caused by each individual nodes playbackRate not correctly being marked as being updated when the global playbackRate is changed.

I've pushed a fix for this now (tagged and published to npm as v0.34.1).

I'll close this issue for now, but please feel free to reopen it if the issue persists.

Kind regards,
Matt

**Closed by MatthewShotton** 2017-03-22 10:45 UTC
