### ISSUE TITLE
registerCallback("ended", function(){console.log("Playback ended");}); is not happen

### ISSUE THREAD

**Issue by Statfine** [bbc/VideoContext#22] opened 2017-03-17 03:13 UTC
const canvas = document.getElementById('canvas');
 this.ctx = new VideoContext(canvas);
 this.ctx.registerCallback("ended", function(){console.log("Playback ended");});

but when ctx.currentTime == ctx.duration the callback is not happen,there is no console

**Comment by MatthewShotton** [comment] 2017-03-17 10:19
Hi!

Thanks for finding that.
The bug was caused by an embarrassing typo. It should be fixed in v0.33.1 which has been published to npm now as well.

Kind regards,
Matt

**Closed by MatthewShotton** 2017-03-17 10:19 UTC
Labels: bug
